cd to SHARED_DRIVE, run exe with full path to /Applications,etc
If not, on the laptop (but not on the desktop) we get

```
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 20, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 462, in install
  File "PyInstaller/loader/pyimod02_importers.py", line 122, in __init__
ImportError: Cannot load frozen modules.
[45246] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```